<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>10.0.1</Version>
    <Authors>BriareosTM</Authors>
    <Company>BStorm</Company>
    <Description>
		Simple classe de connexion au bases de donnée proposant des méthodes d'extension sur le type DbConnection
		ExecuteScalar(Async), ExecuteNonQuery(Async), ExecuteReader(Async)
	</Description>
    <Copyright>Morre Thierry Cognitic/BStorm</Copyright>
    <PackageProjectUrl>https://github.com/TMCognitic/BStorm.Tools.Database</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TMCognitic/BStorm.Tools.Database</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
